In [1]:
pip install transformers

In [2]:
from transformers import pipeline

sentiment_analyzer = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [5]:
raw_text = [
            "I loved the visualization of the course",
            "I hate this so much"
]

In [6]:
sentiment_analyzer(raw_text)

[{'label': 'POSITIVE', 'score': 0.9998599290847778},
 {'label': 'NEGATIVE', 'score': 0.9995144605636597}]

### Tokenizer

In [17]:
from transformers import AutoTokenizer

checkpoint = "distilbert/distilbert-base-uncased-finetuned-sst-2-english"

tokenizer = AutoTokenizer.from_pretrained(checkpoint)

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [18]:
tokenizer.vocab

{'stretches': 14082,
 'disciplines': 12736,
 'gerard': 11063,
 'interested': 4699,
 '[unused677]': 682,
 'isolated': 7275,
 'knockout': 11369,
 'aggregator': 24089,
 'rockies': 22366,
 'synth': 24203,
 'publicized': 24928,
 '1839': 10011,
 '##cope': 16186,
 'flora': 10088,
 'samsung': 19102,
 '##ং': 29882,
 '##ᵥ': 30045,
 'pale': 5122,
 'planets': 11358,
 '##ile': 9463,
 'folk': 5154,
 'swansea': 16085,
 'detainees': 26485,
 'flights': 7599,
 '##龍': 30508,
 'memorials': 22899,
 '##tea': 27058,
 'hairy': 15892,
 'φ': 1176,
 'υ': 1175,
 'systematic': 11778,
 'inputs': 20407,
 'richardson': 9482,
 '##mbo': 13344,
 'bumps': 18548,
 '##∨': 30130,
 'sticking': 13423,
 '##weight': 11179,
 'clever': 12266,
 'hellenic': 23122,
 '##sters': 15608,
 'stalled': 20659,
 '1760': 19096,
 '##kt': 25509,
 'secrecy': 20259,
 'symphonic': 18957,
 '[unused547]': 552,
 'ronald': 8923,
 '##pan': 9739,
 'annum': 28907,
 'mechanically': 27846,
 'ə': 1114,
 'celebrated': 6334,
 'tuna': 24799,
 'reply': 7514,
 '

In [19]:
tokenizer.vocab_size

30522

In [28]:
import tensorflow as tf

token_ids = tokenizer(raw_text, padding=True, truncation=True, return_tensors='tf')
token_ids

{'input_ids': <tf.Tensor: shape=(2, 10), dtype=int32, numpy=
array([[ 101, 1045, 3866, 1996, 5107, 3989, 1997, 1996, 2607,  102],
       [ 101, 1045, 5223, 2023, 2061, 2172,  102,    0,    0,    0]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 10), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0]], dtype=int32)>}

#### Model

In [29]:
from transformers import TFAutoModel

model = TFAutoModel.from_pretrained(checkpoint)

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFDistilBertModel: ['classifier.weight', 'classifier.bias', 'pre_classifier.bias', 'pre_classifier.weight']
- This IS expected if you are initializing TFDistilBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFDistilBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.


In [31]:
output = model(token_ids)
output

TFBaseModelOutput(last_hidden_state=<tf.Tensor: shape=(2, 10, 768), dtype=float32, numpy=
array([[[ 0.68294704, -0.02718455,  0.06692699, ...,  0.44704378,
          1.1086261 , -0.21708146],
        [ 0.91231227,  0.00324705, -0.05076834, ...,  0.35861838,
          1.1493641 , -0.12122649],
        [ 1.034942  ,  0.09335275,  0.12378907, ...,  0.39532068,
          1.0982642 , -0.20298754],
        ...,
        [ 0.7117936 , -0.07394341, -0.14772573, ...,  0.40631843,
          1.1902714 , -0.16201118],
        [ 0.7310011 , -0.04416139,  0.02170686, ...,  0.46344396,
          0.84503376, -0.14935546],
        [ 1.3220476 ,  0.03905301,  0.5222739 , ...,  0.51244414,
          0.7404256 , -0.6619572 ]],

       [[-0.30882215,  0.73317605, -0.18605004, ..., -0.13053794,
         -0.936004  , -0.04329737],
        [-0.33396977,  0.9830436 , -0.09462053, ..., -0.3824745 ,
         -0.6175635 ,  0.20076823],
        [-0.16871417,  0.87811613, -0.11165849, ..., -0.23800467,
         -0.7

In [32]:
output.last_hidden_state.shape

TensorShape([2, 10, 768])

Bachbone + head

In [35]:
from transformers import TFAutoModelForSequenceClassification

model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint)
model

All PyTorch model weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


### post preprocessing

In [37]:
output2 = model(token_ids) # show logits **
output2

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-4.280249 ,  4.5927954],
       [ 4.2140603, -3.4158008]], dtype=float32)>, hidden_states=None, attentions=None)

In [38]:
import tensorflow as tf

predictions = tf.math.softmax(output2.logits, axis=-1)
predictions

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.4009565e-04, 9.9985993e-01],
       [9.9951446e-01, 4.8549261e-04]], dtype=float32)>

In [41]:
tf.argmax(predictions, axis=-1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 0])>

In [42]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

### Tokenization

# word tokenizer

In [44]:
"I loved the visualization in the course, it's too nice to meet you!".split()

['I',
 'loved',
 'the',
 'visualization',
 'in',
 'the',
 'course,',
 "it's",
 'too',
 'nice',
 'to',
 'meet',
 'you!']

In [47]:
!pip install nltk

In [48]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

word_tokenize("I loved the visualization in the course, it's too nice to meet you!")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


['I',
 'loved',
 'the',
 'visualization',
 'in',
 'the',
 'course',
 ',',
 'it',
 "'s",
 'too',
 'nice',
 'to',
 'meet',
 'you',
 '!']

In [49]:
list("I loved the visualization in the course, it's too nice to meet you!")

['I',
 ' ',
 'l',
 'o',
 'v',
 'e',
 'd',
 ' ',
 't',
 'h',
 'e',
 ' ',
 'v',
 'i',
 's',
 'u',
 'a',
 'l',
 'i',
 'z',
 'a',
 't',
 'i',
 'o',
 'n',
 ' ',
 'i',
 'n',
 ' ',
 't',
 'h',
 'e',
 ' ',
 'c',
 'o',
 'u',
 'r',
 's',
 'e',
 ',',
 ' ',
 'i',
 't',
 "'",
 's',
 ' ',
 't',
 'o',
 'o',
 ' ',
 'n',
 'i',
 'c',
 'e',
 ' ',
 't',
 'o',
 ' ',
 'm',
 'e',
 'e',
 't',
 ' ',
 'y',
 'o',
 'u',
 '!']

In [51]:
tuple("I loved the visualization in the course, it's too nice to meet you!")

('I',
 ' ',
 'l',
 'o',
 'v',
 'e',
 'd',
 ' ',
 't',
 'h',
 'e',
 ' ',
 'v',
 'i',
 's',
 'u',
 'a',
 'l',
 'i',
 'z',
 'a',
 't',
 'i',
 'o',
 'n',
 ' ',
 'i',
 'n',
 ' ',
 't',
 'h',
 'e',
 ' ',
 'c',
 'o',
 'u',
 'r',
 's',
 'e',
 ',',
 ' ',
 'i',
 't',
 "'",
 's',
 ' ',
 't',
 'o',
 'o',
 ' ',
 'n',
 'i',
 'c',
 'e',
 ' ',
 't',
 'o',
 ' ',
 'm',
 'e',
 'e',
 't',
 ' ',
 'y',
 'o',
 'u',
 '!')

In [53]:
tokenizer.model_max_length # context size

512

#### sub-word tokenizer

In [54]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(checkpoint)

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [55]:
tokenizer.vocab_size

30522

In [57]:
tokenizer("I loved the visualization in the course, it's too nice to meet you!")

{'input_ids': [101, 1045, 3866, 1996, 5107, 3989, 1999, 1996, 2607, 1010, 2009, 1005, 1055, 2205, 3835, 2000, 3113, 2017, 999, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

what model do is :
1- tokenize
2-map each token

In [63]:
tokenizer.tokenize("I loved the visualization in the course, it's too nice to meet you!", add_special_tokens=True)

['[CLS]',
 'i',
 'loved',
 'the',
 'visual',
 '##ization',
 'in',
 'the',
 'course',
 ',',
 'it',
 "'",
 's',
 'too',
 'nice',
 'to',
 'meet',
 'you',
 '!',
 '[SEP]']

In [64]:
tokenizer.vocab['[SEP]']

102

In [66]:
tokenizer.vocab['i']

1045

In [70]:
tokenizer.convert_ids_to_tokens([101, 104])

['[CLS]', '[unused99]']

In [69]:
tokenizer.all_special_tokens

['[UNK]', '[SEP]', '[PAD]', '[CLS]', '[MASK]']